### ISSUE TITLE
Add support for private registry

### ISSUE THREAD

**Issue by alexmngn** [azu/can-npm-publish#1]
Would be nice to have support for private registry. ATM it only checks on npmjs.com. 

`npm get registry` returns the current registry set in `.npmrc` which could be replaced by in your fetch. I might create a PR if I have the time for it.

**Comment by azu** [comment]
Currently, just fetch pacakge info from npm registry REST API.

https://github.com/azu/can-npm-publish/blob/1c9a1b4bb19de3e48c5dd6c60b4de041481c2575/lib/can-npm-publish.js#L44-L47

Private registry may require CREDENTIAL for requesting.
For example, [Artifactory](https://www.jfrog.com/confluence/display/RTF/Npm+Registry "Artifactory") require authentication.

I think that we can use `npm view --json` instead of `fetch` API.

- [view | npm Documentation](https://docs.npmjs.com/cli/view "view | npm Documentation")

**Comment by azu** [comment]
Resolved by #3 

- [v1.1.0](https://github.com/azu/can-npm-publish/releases/tag/v1.1.0 "v1.1.0")
